name: 'Replicated download customer license'
description: 'Download a Customer License'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer-name:
    description: 'Name of the customer.'
    required: true
outputs:
  license: # id of the output
    description: 'Contains the yaml license.'
runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - customer
    - download-license
    - --customer="${{ inputs.customer-name }}"
    - --output=json
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}