name: 'Replicated archive Customer'
description: 'Archive a customer'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer:
    description: 'The Customer Name or ID.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - customer
    - archive
    - --customer=${{ inputs.customer }}
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}