name: 'Replicated CLI wait for Cluster'
description: 'CLI: Wait for a cluster to be running'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  cluster-id:
    description: 'Cluster id to wait for to be running'
    required: true
outputs:
  cluster-status: # status of the cluster
    description: 'Contains the cluster status.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}
    CLUSTER_ID: ${{ inputs.cluster-id }}