apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: spooky-app
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: spooky-app
    chartVersion: $VERSION

  # helmVersion identifies the Helm Version used to render the Chart. Default is v2.
  helmVersion: v3
  values:
    image:
      tag: latest

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true
