name: 'Replicated get customer license id'
description: 'Get a Customer License ID'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer:
    description: 'The Customer Name or ID'
    required: true
outputs:
  license-id: # id of the output
    description: 'Contains the license id.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - customer
    - download-license
    - --customer=${{ inputs.customer }}
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}