name: 'Replicated Create Customer and Download License'
description: 'Replicated Create Customer and Download License'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer-name:
    description: 'Name of the customer.'
    required: true
  customer-email:
    description: 'Email of the customer.'
    required: false
  channel:
    description: 'Channel to assign the customer to.'
    required: true
    default: '${GITHUB_REF}'
outputs:
  license: # id of the output
    description: 'Contains the yaml license.'
    value: ${{ steps.download-customer-license.outputs.license }}
runs:
  using: "composite"
  steps:
    - name: 'Replicated create customer'
      id: 'create-customer'
      uses: './.github/actions/create-customer'
      with:
        replicated-app: ${{ inputs.replicated-app }}
        replicated-api-token: ${{ inputs.replicated-api-token }}
        customer-name: ${{ inputs.customer-name }}
        customer-email: ${{ inputs.customer-email }}
        channel: ${{ inputs.channel }}
    - name: Get Customer Id
      id: get-customer-id
      shell: bash
      run: |
        echo "::set-output name=customer-id::$(echo '${{ steps.create-customer.outputs.customer }}' | jq -r '.id')"
    - name: 'Replicated download customer license'
      id: 'download-customer-license'
      uses: './.github/actions/download-license'
      with:
        replicated-app: ${{ inputs.replicated-app }}
        replicated-api-token: ${{ inputs.replicated-api-token }}
        customer: ${{ steps.get-customer-id.outputs.customer-id }}