name: 'Replicated Create Customer and Download License'
description: 'Replicated Create Customer and Download License'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  customer-name:
    description: 'Name of the customer.'
    required: true
  customer-email:
    description: 'Email of the customer.'
    required: false
  channel:
    description: 'Channel to assign the customer to.'
    required: true
    default: '${GITHUB_REF}'
runs:
  using: "composite"
  steps:
    - name: My first step
      uses: octo-org/action-name@main
    - name: My backup step
      if: ${{ failure() }}
      uses: actions/heroku@1.0.0