apiVersion: v2
name: spooky-app
description: A Helm chart for Kubernetes
dependencies:
- name: replicated
  version: "0.0.1-alpha.15"
  repository: "oci://registry.replicated.com/library"


type: application
version: 0.1.4

appVersion: "1.16.4"
