name: 'Replicated CLI archive Channel'
description: 'CLI: Archive a channel'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  channel-id:
    description: 'The id of the channel to archive.'
    required: true
runs:
  using: 'docker'
  image: '../Dockerfile'
  args:
    - channel
    - rm
    - ${{ inputs.channel-id }}
  env:
    REPLICATED_APP: ${{ inputs.replicated-app }}
    REPLICATED_API_TOKEN: ${{ inputs.replicated-api-token }}