name: 'Replicated archive Channel'
description: 'Archive a channel'
inputs:
  replicated-app:
    description: 'Replicated App Slug.'
    required: true
    default: ''
  replicated-api-token:
    description: 'Replicated API Token.'
    required: true
    default: ''
  channel-name:
    description: 'The name of the Channel to archive.'
    required: true
runs:
  using: "composite"
  steps:
  - name: 'CLI: Inspect a channel'
    id: 'cli-inspect-channel'
    uses: './.github/actions/cli-inspect-channel'
    with:
      replicated-app: ${{ inputs.replicated-app }}
      replicated-api-token: ${{ inputs.replicated-api-token }}
      channel-name: ${{ inputs.channel-name }}
  - name: 'Replicated CLI archive Channel'
    id: 'cli-archive-channel'
    uses: './.github/actions/cli-archive-channel'
    with:
      replicated-app: ${{ inputs.replicated-app }}
      replicated-api-token: ${{ inputs.replicated-api-token }}
      channel-id: ${{ steps.cli-inspect-channel.outputs.channel-id }}