apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-config"
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: preflight-sample
    spec:
      collectors:
        - registryImages:
            namespace: {{ .Release.Namespace | quote }}
            imagePullSecret:
              name: spooky-registry
            images:
              - "alpine:3.9"
      analyzers:
        - clusterVersion:
            outcomes:
              - fail:
                  when: "< 1.22.0"
                  message: The application requires at least Kubernetes 1.22.0, and recommends 1.23.0.
                  uri: https://kubernetes.io
              - warn:
                  when: "< 1.23.0"
                  message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.18.0 or later.
                  uri: https://kubernetes.io
              - pass:
                  message: Your cluster meets the recommended and required versions of Kubernetes.
        - registryImages:
            checkName: Private Registry Images
            outcomes:
              - fail:
                  when: "missing > 0"
                  message: Images are missing from registry
              - warn:
                  when: "errors > 0"
                  message: Failed to check if images are present in registry
              - pass:
                  message: All images are present in registry
