name: cron

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  push-to-replicated:
    runs-on: ubuntu-22.04
    outputs:
      channel-slug: ${{ steps.create-release.outputs.channel-slug}}
      release-sequence: ${{ steps.create-release.outputs.release-sequence}}
    steps:
      - uses: actions/checkout@v3

      - name: Define App Version
        run: echo "APP_VERSION=0.0.1-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Define Channel Name
        run: echo "CHANNEL_NAME=${{ github.ref_name }}-${GITHUB_SHA::7}-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u -d kots \
            --app-version=${{ env.APP_VERSION }} \
            --version=${{ env.APP_VERSION }}

      - name: Update the HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'kots/spooky-app-chart.yaml'
          find: '$VERSION'
          replace: '${{ env.APP_VERSION }}'
          regex: false

      - name: Create Replicated Release
        id: create-release
        uses: replicatedhq/replicated-actions/create-release@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: ./kots
          promote-channel: ${{ env.CHANNEL_NAME }}
          version: ${{ env.APP_VERSION }}

  compatibility-matrix:
    needs: push-to-replicated
    strategy:
      fail-fast: false
      matrix:
        cluster: [{distribution: kind, version: v1.25.3, installation-method: kots},
                  {distribution: kind, version: v1.25.8, installation-method: helm},
                  {distribution: kind, version: v1.26.3, installation-method: helm},
                  {distribution: kind, version: v1.27.0, installation-method: helm},
                  {distribution: k3s, version: v1.26, installation-method: kots},
                  {distribution: k3s, version: v1.25, installation-method: kots},
                  {distribution: eks, version: 1.27, installation-method: helm}]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Define App Version
        run: echo "APP_VERSION=0.0.1-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create Customer 
        id: create-customer
        uses: replicatedhq/replicated-actions/create-customer@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          customer-name: ${{ github.ref_name }}-${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          channel-slug: ${{ needs.push-to-replicated.outputs.channel-slug }}
          customer-email: ${{ github.ref_name }}@example.com
          license-type: prod

      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/replicated-actions/create-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          cluster-name: ${{ github.ref_name }}-${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          timeout-minutes: 20
          ttl: 30m
          tags: |
            - key: "cron"
              value: "${{ github.run_id }}"

      - name: Deploy the app
        uses: replicatedhq/replicated-actions/kots-install@v1
        if: ${{ matrix.cluster.installation-method == 'kots' }}
        with:
          kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
          app-slug: ${{ secrets.REPLICATED_APP }}/${{ needs.push-to-replicated.outputs.channel-slug }}
          license-file: ${{ steps.create-customer.outputs.license-file }}
          app-version-label: ${{ env.APP_VERSION }}

      - name: Deploy the app
        uses: replicatedhq/replicated-actions/helm-install@v1
        if: ${{ matrix.cluster.installation-method == 'helm'}}
        with:
          kubeconfig: ${{ steps.create-cluster.outputs.cluster-kubeconfig }}
          helm-path: "helm"
          registry-username: ${{ github.ref_name }}@example.com
          registry-password: ${{ steps.create-customer.outputs.license-id }}
          chart: oci://registry.replicated.com/${{ secrets.REPLICATED_APP }}/${{ needs.push-to-replicated.outputs.channel-slug }}/spooky-app
          name: 'spooky-app'
          version: ${{ env.APP_VERSION }}
          namespace: 'default'
          values: |
            image:
              tag: latest

      - name: Run a test
        # mask the kubeconfig so it doesn't show up in the logs
        run: |
          echo "Running a test"
          echo "${{ steps.create-cluster.outputs.cluster-kubeconfig }}" > kubeconfig.yaml
          sleep 60
          kubectl port-forward svc/spooky-app --pod-running-timeout=2m --kubeconfig='./kubeconfig.yaml' 8080:80 &
          sleep 120
          curl -f http://localhost:8080
          echo "Test complete"

      - name: Remove Cluster
        id: remove-cluster
        if: always()
        uses: replicatedhq/replicated-actions/remove-cluster@v1
        continue-on-error: true # It could be that the cluster is already removed
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}

      - name: Archive Customer
        id: archive-customer
        if: always()
        uses: replicatedhq/replicated-actions/archive-customer@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          customer-id:  ${{ steps.create-customer.outputs.customer-id }}

  cleanup-channel:
    needs:
      - compatibility-matrix
      - push-to-replicated
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Archive Replicated Channel
        uses: replicatedhq/replicated-actions/archive-channel@v1
        if: always()
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          channel-slug: ${{ needs.push-to-replicated.outputs.channel-slug }}    
          
