name: development

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main

jobs:
  compatibility-matrix:
    strategy:
      fail-fast: false
      matrix:
        cluster: [ {distribution: kind, version: v1.25.3}]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u

      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/compatibility-actions/prepare-cluster@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          chart: spooky-app-0.1.4.tgz
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          helm-chart-name: spooky-app
          helm-values: |
            image:
              tag: latest

      - name: Run tests
        id: run-tests
        run: c11y-tests/test.sh