name: release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  get-customer-instances:
    outputs:
      matrix: ${{ steps.get-customer-instances.outputs.matrix}}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get Customer Instances
        id: get-customer-instances
        uses: replicatedhq/replicated-actions/get-customer-instances@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}

  compatibility-matrix:
    needs: get-customer-instances
    if: ${{ !contains(needs.get-customer-instances.outputs.matrix, '[]') }}
    strategy:
      fail-fast: false
      matrix:
        cluster: ${{ fromJson(needs.get-customer-instances.outputs.matrix) }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u

      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/compatibility-actions/prepare-cluster@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          chart: spooky-app-0.1.4.tgz
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          helm-chart-name: spooky-app
          helm-values: |
            image:
              tag: latest

  promote_to_stable:
    needs: 
      - compatibility-matrix
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u -d kots \
            --app-version=${{ github.ref_name }} \
            --version=${{ github.ref_name }}

      - name: Update the HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'kots/spooky-app-chart.yaml'
          find: '$VERSION'
          replace: '${{ github.ref_name }}'
          regex: false

      - name: Create Replicated Release
        id: create-release
        uses: replicatedhq/replicated-actions/create-release@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: ./kots
          promote-channel: Stable
          version: ${{ github.ref_name }}
          
