name: release

on:
  push:
    tags:
    - "v*.*.*"

jobs:
  get-customer-instances:
    outputs:
      matrix: ${{ steps.get-customer-instances.outputs.matrix}}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get Customer Instances
        id: get-customer-instances
        uses: replicatedhq/compatibility-actions/get-customer-instances@v0
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}

  compatibility-matrix:
    needs: get-customer-instances
    strategy:
      fail-fast: false
      matrix:
        cluster: ${{ fromJson(needs.get-customer-instances.outputs.matrix) }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Define App Version
        shell: bash
        run: echo "APP_VERSION=0.0.1-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_RUN_ID}${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u -d kots \
            --app-version=0.0.1-${{ github.ref_name }} \
            --version=${{ env.APP_VERSION }}

      - name: Update the HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'kots/spooky-app-chart.yaml'
          find: '$VERSION'
          replace: ${{ env.APP_VERSION }}
          regex: false

      - name: Smoke Test
        id: smoke-test
        uses: replicatedhq/compatibility-actions/smoke-test@v0
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: kots
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          installation-method: helm
          test-script: ./c11y-tests/test.sh
          helm-chart-name: spooky-app
          helm-values: |
            image:
              tag: latest

  promote_to_stable:
    needs: 
      - compatibility-matrix
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u -d kots \
            --app-version=${{ github.ref_name }} \
            --version=${{ github.ref_name }}

      - name: Update the HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'kots/spooky-app-chart.yaml'
          find: '$VERSION'
          replace: '${{ github.ref_name }}'
          regex: false

      - name: Create Replicated Release
        id: create-release
        uses: replicatedhq/compatibility-actions/create-release@v0
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          yaml-dir: ./kots
          promote-channel: Stable
          version: ${{ github.ref_name }}
          
