name: staging-test

on:
  workflow_dispatch:

jobs:
  compatibility-matrix:
    strategy:
      fail-fast: false
      matrix:
        cluster: [{distribution: kind, version: 1.27.0},
                  {distribution: k3s, version: 1.26},
                  {distribution: helmvm, version: 1.27},
                  {distribution: openshift, version: 4.13.0-okd},
                  {distribution: eks, version: 1.27}]
    runs-on: ubuntu-22.04
    steps:
      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/replicated-actions/create-cluster@v0
        with:
          replicated-api-endpoint: https://api.staging.replicated.com/vendor/v3
          api-token: ${{ secrets.REPLICATED_TOKEN_STAGING }}
          kubernetes-distribution: ${{ matrix.cluster.distribution }}
          kubernetes-version: ${{ matrix.cluster.version }}
          cluster-name: ${{ matrix.cluster.distribution }}-${{ matrix.cluster.version }}
          timeout-minutes: 20
          ttl: 30m

      - name: Run a test
        # mask the kubeconfig so it doesn't show up in the logs
        run: |
          echo "Running a test"
          echo "${{ steps.create-cluster.outputs.cluster-kubeconfig }}" > kubeconfig.yaml
          kubectl get po --kubeconfig='./kubeconfig.yaml'
          echo "Test complete"

      - name: Remove Cluster
        id: remove-cluster
        if: always()
        uses: replicatedhq/replicated-actions/remove-cluster@v0
        continue-on-error: true # It could be that the cluster is already removed
        with:
          replicated-api-endpoint: https://api.staging.replicated.com/vendor/v3
          api-token: ${{ secrets.REPLICATED_TOKEN_STAGING }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}  
      
