name: test-create-postgres
on:
  workflow_dispatch:

jobs:
  test-create-postgres:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/compatibility-actions/create-cluster@joshd/sc-101450/cloud-addons-github-action
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: eks
      - name: Create Postgres
        id: create-postgres
        uses: replicatedhq/compatibility-actions/create-postgres@joshd/sc-101450/cloud-addons-github-action
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
      - name: Echo add-on details
        run: |
          echo "Cluster ID: ${{ steps.create-cluster.outputs.cluster-id }}"
          echo "Postgres URI: ${{ steps.create-postgres.outputs.uri }}"
      - name: Delete Cluster
        uses: replicatedhq/compatibility-actions/remove-cluster@joshd/sc-101450/cloud-addons-github-action
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
