name: test-customer

on:
  workflow_dispatch:

jobs:
  test-customer:
    runs-on: ubuntu-22.04
    steps:
      - name: Create Customer 
        id: create-customer
        uses: replicatedhq/replicated-actions/create-customer@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          customer-name: Testing with entitlements
          channel-slug: stable
          customer-email: test@example.com
          license-type: prod
          entitlements: |
            - name: "number-of-users"
              value: "10"
