name: test-create-cluster
on:
  workflow_dispatch:

jobs:
  test-create-cluster:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create Cluster
        id: create-cluster
        uses: replicatedhq/compatibility-actions/create-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: eks
      - name: Remove Cluster
        id: remove-cluster
        uses: replicatedhq/compatibility-actions/remove-cluster@v1
        with:
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          cluster-id: ${{ steps.create-cluster.outputs.cluster-id }}
