name: test-prepare-cluster
on:
  workflow_dispatch:

jobs:
  test-upgrade-cluster:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/compatibility-actions/prepare-cluster@v1
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: eks
          kubernetes-version: 1.25
          yaml-dir: ./kots
          kots-wait-duration: 5m

