name: test-prepare-cluster
on:
  workflow_dispatch:

jobs:
  test-prepare-cluster:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Package Helm Chart for Replicated
        id: package-helm-chart
        run: |
          helm package spooky-app -u -d kots \
            --app-version=${{ github.ref_name }} \
            --version=0.0.1

      - name: Update the HelmChart kind
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: 'kots/spooky-app-chart.yaml'
          find: '$VERSION'
          replace: '0.0.1'
          regex: false
          
      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/replicated-actions/prepare-cluster@joshd/prepare-cluster-pin-kots-version
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: k3s
          yaml-dir: ./kots
          kots-wait-duration: 5m
          customer-entitlements: |
            - name: "number-of-users"
              value: "10"

