name: test-prepare-cluster
on:
  workflow_dispatch:

jobs:
  test-prepare-cluster:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Cluster
        id: prepare-cluster
        uses: replicatedhq/compatibility-actions/prepare-cluster@emosbaugh/e2e-test-prepare-cluster
        with:
          app-slug: ${{ secrets.REPLICATED_APP }}
          api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          kubernetes-distribution: eks
          kubernetes-version: 1.28
          yaml-dir: ./kots
          kots-wait-duration: 5m
          customer-entitlements: |
            - name: "number-of-users"
              value: "10"

